-- BioTwin server-side schema for hosted Supabase Postgres.
--
-- BioTwin keeps authentication and authorization in FastAPI. The browser must
-- never access these tables directly with Supabase anon/authenticated keys.

create table if not exists public.users (
    id text primary key,
    email text not null unique,
    password text not null,
    name text not null,
    profile jsonb not null default '{}'::jsonb,
    sequence integer not null default 0
);

create table if not exists public.measurements (
    id bigint generated by default as identity primary key,
    user_id text not null references public.users(id) on delete cascade,
    event_time double precision not null,
    ingest_time double precision not null,
    provenance text not null,
    dedupe_key text not null,
    sequence integer not null,
    payload jsonb not null,
    constraint uq_measurements_user_dedupe unique (user_id, dedupe_key)
);

create index if not exists ix_measurements_user_id
    on public.measurements(user_id);
create index if not exists ix_measurements_event_time
    on public.measurements(event_time);
create index if not exists ix_measurements_user_time
    on public.measurements(user_id, event_time desc, sequence desc);

create table if not exists public.documents (
    user_id text not null references public.users(id) on delete cascade,
    kind text not null,
    key text not null,
    payload jsonb not null,
    primary key (user_id, kind, key)
);

create table if not exists public.sessions (
    hash text primary key,
    user_id text not null references public.users(id) on delete cascade,
    expires double precision not null
);

create index if not exists ix_sessions_user_id on public.sessions(user_id);
create index if not exists ix_sessions_expires on public.sessions(expires);

create table if not exists public.conversations (
    id text primary key,
    user_id text not null references public.users(id) on delete cascade,
    question text not null,
    answer text,
    gemini_answer text,
    created_at double precision not null,
    completed_at double precision,
    mode text not null,
    notice text,
    model text,
    context jsonb not null
);

create index if not exists ix_conversations_user_id
    on public.conversations(user_id);
create index if not exists ix_conversations_created_at
    on public.conversations(created_at);

create table if not exists public.outbox (
    id bigint generated by default as identity primary key,
    provider text not null,
    payload jsonb not null,
    status text not null,
    attempts integer not null default 0,
    available double precision not null,
    error text
);

create index if not exists ix_outbox_status_available
    on public.outbox(status, available);

-- Defense in depth: BioTwin's FastAPI server is the only supported data API.
-- Direct access through Supabase browser roles remains unavailable.
alter table public.users enable row level security;
alter table public.measurements enable row level security;
alter table public.documents enable row level security;
alter table public.sessions enable row level security;
alter table public.conversations enable row level security;
alter table public.outbox enable row level security;

revoke all on table public.users from anon, authenticated;
revoke all on table public.measurements from anon, authenticated;
revoke all on table public.documents from anon, authenticated;
revoke all on table public.sessions from anon, authenticated;
revoke all on table public.conversations from anon, authenticated;
revoke all on table public.outbox from anon, authenticated;
revoke all on sequence public.measurements_id_seq from anon, authenticated;
revoke all on sequence public.outbox_id_seq from anon, authenticated;

